name: 'Database Lab: realistic DB testing in CI'
branding:
  icon: 'database'  
  color: 'orange'
description: 'Check database migrations with the Database Lab Engine'
inputs:
  owner:
    description: 'The owner of the repository to check'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The repo to check'
    required: true
    default: ${{ github.event.repository.name }}
  ref:
    description: 'The input represents a ref parameter, which can be a SHA, branch, or tag'
    required: true
    default: ${{ github.ref }}
  pull_request:
    description: 'Link to the pull request'
    required: false
    default: ${{ github.event.pull_request.html_url }}
  compare:
    description: 'The compare link'
    required: false
    default: ${{ github.event.compare }}
  commit_sha:
    description: 'Commit SHA'
    required: false
    default: ${{ github.event.after }}
  author_name:
    description: 'Author name'
    required: false
    default: ${{ github.event.head_commit.author.name }}
  commands:
    description: 'List of commands to run DB migrations'
    required: true
  dbname:
    description: 'The database that the workflow is running with'
    required: false
    default: ""
  migration_envs:
    description: 'List of environment variables that will be set during migrations running'
    required: false
  download_artifacts:
    description: 'Option to download artifacts'
    required: false
    default: "false"

  observation_interval:
    description: 'Observation interval'
    required: false
    default: "10"
  max_lock_duration:
    description: 'Max lock duration'
    required: false
    default: "10"
  max_duration:
    description: 'Max duration'
    required: false
    default: "3600"

outputs:
  response:
    description: 'The result of migration checks'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_PULL_REQUEST: ${{ inputs.pull_request }}
        INPUT_COMPARE: ${{ inputs.compare }}
        INPUT_COMMIT_SHA: ${{ inputs.commit_sha }}
        INPUT_AUTHOR_NAME: ${{ inputs.author_name }}
        INPUT_COMMANDS: ${{ inputs.commands }}
        INPUT_DBNAME: ${{ inputs.dbname }}
        INPUT_MIGRATION_ENVS: ${{ inputs.migration_envs }}
        INPUT_DOWNLOAD_ARTIFACTS: ${{ inputs.download_artifacts }}
        INPUT_OBSERVATION_INTERVAL: ${{ inputs.observation_interval }}
        INPUT_MAX_LOCK_DURATION: ${{ inputs.max_lock_duration }}
        INPUT_MAX_DURATION: ${{ inputs.max_duration }}
